//! Discovers the shipped locales and generates the catalog table.
//!
//! Every `locales/<tag>/mikrotik-rif.ftl` becomes a compile-time embedded
//! resource, so adding a language means dropping the file in place: there is no
//! Rust registry to keep in sync and no runtime directory to depend on.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let locales = manifest.join("locales");
    println!("cargo:rerun-if-changed=locales");
    println!("cargo:rerun-if-changed=app.rc");
    println!("cargo:rerun-if-changed=assets/icon/icon.ico");

    // Embeds the application icon into the .exe on Windows. On other
    // hosts/targets this is a no-op (`NotWindows`), and a missing resource
    // compiler is tolerated so Linux/macOS builds never break because of it.
    embed_resource::compile("app.rc", embed_resource::NONE)
        .manifest_optional()
        .unwrap();

    let mut discovered = Vec::new();
    if let Ok(entries) = fs::read_dir(&locales) {
        for entry in entries.flatten() {
            let directory = entry.path();
            if !directory.is_dir() {
                continue;
            }
            let Some(tag) = directory.file_name().and_then(|name| name.to_str()) else {
                continue;
            };
            let file = directory.join("mikrotik-rif.ftl");
            if is_language_tag(tag) && file.is_file() {
                discovered.push((tag.to_owned(), file));
            }
        }
    }
    discovered.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("/// Every locale discovered under `locales/`, sorted by language tag.\n");
    generated.push_str("/// Each entry pairs the language tag with the embedded Fluent source.\n");
    generated.push_str("pub const SHIPPED: &[(&str, &str)] = &[\n");
    for (tag, path) in &discovered {
        // `include_str!` needs a literal, and Windows paths need escaping.
        let literal = path.to_string_lossy().replace('\\', "\\\\");
        let _ = writeln!(generated, "    (\"{tag}\", include_str!(\"{literal}\")),");
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("locales.rs"), generated).expect("write locales.rs");
}

/// Whether a directory name is a plausible BCP-47 tag such as `en` or `zh-Hans`.
///
/// This only filters obvious non-locale entries; the tag is validated for real
/// when the catalog is built.
fn is_language_tag(tag: &str) -> bool {
    !tag.is_empty()
        && tag.split(['-', '_']).all(|part| {
            !part.is_empty() && part.len() <= 8 && part.chars().all(|c| c.is_ascii_alphanumeric())
        })
}
