//! Discovers the shipped locales and generates the catalog table.
//!
//! Every `locales/<tag>/mikrotik-rif.ftl` becomes a compile-time embedded
//! resource, so adding a language means dropping the file in place: there is no
//! Rust registry to keep in sync and no runtime directory to depend on.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let locales = manifest.join("locales");
    println!("cargo:rerun-if-changed=locales");
    println!("cargo:rerun-if-changed=app.rc");
    println!("cargo:rerun-if-changed=assets/icon/icon.ico");

    // Embeds the application icon into the .exe on Windows. On other
    // hosts/targets this is a no-op (`NotWindows`), and a missing resource
    // compiler is tolerated so Linux/macOS builds never break because of it.
    embed_resource::compile("app.rc", embed_resource::NONE)
        .manifest_optional()
        .unwrap();

    let mut discovered = Vec::new();
    if let Ok(entries) = fs::read_dir(&locales) {
        for entry in entries.flatten() {
            let directory = entry.path();
            if !directory.is_dir() {
                continue;
            }
            let Some(tag) = directory.file_name().and_then(|name| name.to_str()) else {
                continue;
            };
            let file = directory.join("mikrotik-rif.ftl");
            if is_language_tag(tag) && file.is_file() {
                discovered.push((tag.to_owned(), file));
            }
        }
    }
    discovered.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("/// Every locale discovered under `locales/`, sorted by language tag.\n");
    generated.push_str("/// Each entry pairs the language tag with the embedded Fluent source.\n");
    generated.push_str("pub const SHIPPED: &[(&str, &str)] = &[\n");
    for (tag, path) in &discovered {
        // `include_str!` needs a literal, and Windows paths need escaping.
        let literal = path.to_string_lossy().replace('\\', "\\\\");
        let _ = writeln!(generated, "    (\"{tag}\", include_str!(\"{literal}\")),");
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("locales.rs"), generated).expect("write locales.rs");

    emit_build_identity();
}

/// Expose the commit this binary was compiled from to the crate.
///
/// The About and Updates screens quote a short build hash so a bug report can
/// name the exact build. `MIKROTIK_RIF_COMMIT` lets CI inject the value when
/// the build happens without a `.git` directory; otherwise the local
/// repository is asked. A missing git (source tarball, packaged build) falls
/// back to `unknown` so the build never fails over build metadata.
fn emit_build_identity() {
    println!("cargo:rerun-if-env-changed=MIKROTIK_RIF_COMMIT");
    // The commit changes when `HEAD` moves; without this the value is only
    // refreshed when some other watched file changes.
    println!("cargo:rerun-if-changed=.git/HEAD");

    let commit = std::env::var("MIKROTIK_RIF_COMMIT")
        .ok()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
        .or_else(git_head)
        .unwrap_or_else(|| "unknown".to_owned());
    println!("cargo:rustc-env=MIKROTIK_RIF_GIT_COMMIT={commit}");

    // Optional release-signing public key (minisign, base64, one line). Empty
    // when the maintainer has not configured signing; the updater then keeps
    // its SHA-256-only behaviour. Read from the environment so the key is not
    // hard-coded in the source tree.
    println!("cargo:rerun-if-env-changed=MIKROTIK_RIF_MINISIGN_PUBKEY");
    let pubkey = std::env::var("MIKROTIK_RIF_MINISIGN_PUBKEY")
        .ok()
        .map(|value| value.trim().to_owned())
        .unwrap_or_default();
    println!("cargo:rustc-env=MIKROTIK_RIF_MINISIGN_PUBKEY={pubkey}");
}

/// `git rev-parse HEAD`, or `None` when git is unavailable or this is not a
/// repository checkout.
fn git_head() -> Option<String> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let commit = String::from_utf8(output.stdout).ok()?.trim().to_owned();
    (!commit.is_empty()).then_some(commit)
}

/// Whether a directory name is a plausible BCP-47 tag such as `en` or `zh-Hans`.
///
/// This only filters obvious non-locale entries; the tag is validated for real
/// when the catalog is built.
fn is_language_tag(tag: &str) -> bool {
    !tag.is_empty()
        && tag.split(['-', '_']).all(|part| {
            !part.is_empty() && part.len() <= 8 && part.chars().all(|c| c.is_ascii_alphanumeric())
        })
}
