//! Localization with Project Fluent.
//!
//! Every user-facing string lives in `locales/<tag>/mikrotik-rif.ftl` and is
//! embedded in the binary at compile time, so the app ships with all locales and
//! reads no files at runtime. The catalog table is generated by `build.rs` from
//! the contents of `locales/`, so adding a language is just dropping a file in
//! place.
//!
//! Look-ups always prefer the selected locale and fall back to the base locale
//! (`en`) for anything a translation does not define, so a partially translated
//! file never leaves the interface blank.

use fluent_bundle::{FluentArgs, FluentBundle, FluentResource};
use unic_langid::LanguageIdentifier;

include!(concat!(env!("OUT_DIR"), "/locales.rs"));

/// Tag used when the system locale is unknown and as the translation fallback.
pub const BASE_LANGUAGE: &str = "en";

/// One locale and its parsed messages.
struct Catalog {
    id: LanguageIdentifier,
    bundle: FluentBundle<FluentResource>,
}

/// The localization state of one running application.
pub struct I18n {
    catalogs: Vec<Catalog>,
    current: usize,
}

impl I18n {
    /// Detect the system locale, falling back to the base language.
    ///
    /// `MIKROTIK_RIF_LANG` overrides detection, which is handy for testing and
    /// for users who want to force a locale.
    #[must_use]
    pub fn detected() -> Self {
        let tag = std::env::var("MIKROTIK_RIF_LANG")
            .ok()
            .filter(|value| !value.trim().is_empty())
            .or_else(sys_locale::get_locale)
            .unwrap_or_default();
        Self::for_language(&tag)
    }

    /// Build the catalog set and select the best match for `tag`.
    #[must_use]
    pub fn for_language(tag: &str) -> Self {
        let catalogs: Vec<Catalog> = SHIPPED
            .iter()
            .map(|(locale, source)| catalog(locale, source))
            .collect();

        let wanted = tag
            .split(['-', '_'])
            .next()
            .unwrap_or(BASE_LANGUAGE)
            .to_ascii_lowercase();
        let current = catalogs
            .iter()
            .position(|catalog| catalog.id.language.as_str() == wanted)
            .or_else(|| {
                catalogs
                    .iter()
                    .position(|catalog| catalog.id.language.as_str() == BASE_LANGUAGE)
            })
            .unwrap_or(0);

        Self { catalogs, current }
    }

    /// Format a message that takes no arguments.
    #[must_use]
    pub fn text(&self, id: &str) -> String {
        self.render(id, &FluentArgs::new())
    }

    /// Format a message whose `$count` variable is a quantity.
    #[must_use]
    pub fn count(&self, id: &str, count: u64) -> String {
        let mut args = FluentArgs::new();
        args.set("count", to_number(count));
        self.render(id, &args)
    }

    /// Format a message with `$position` and `$total`.
    #[must_use]
    pub fn progress(&self, id: &str, position: u64, total: u64) -> String {
        let mut args = FluentArgs::new();
        args.set("position", to_number(position));
        args.set("total", to_number(total));
        self.render(id, &args)
    }

    /// Format a message with caller-provided arguments.
    ///
    /// The selected locale is tried first, then the base locale, then the
    /// identifier itself.
    #[must_use]
    pub fn render(&self, id: &str, args: &FluentArgs<'_>) -> String {
        if let Some(catalog) = self.catalogs.get(self.current)
            && let Some(text) = format_message(&catalog.bundle, id, args)
        {
            return text;
        }
        if let Some(text) = self
            .catalogs
            .iter()
            .find(|catalog| catalog.id.language.as_str() == BASE_LANGUAGE)
            .and_then(|catalog| format_message(&catalog.bundle, id, args))
        {
            return text;
        }
        id.to_owned()
    }
}

/// Look a message up in one bundle and format it, if it is defined there.
fn format_message(
    bundle: &FluentBundle<FluentResource>,
    id: &str,
    args: &FluentArgs<'_>,
) -> Option<String> {
    let message = bundle.get_message(id)?;
    let pattern = message.value()?;
    let mut errors = Vec::new();
    let formatted = bundle.format_pattern(pattern, Some(args), &mut errors);
    Some(strip_isolation(formatted.into_owned()))
}

/// Build one catalog from an embedded Fluent file.
fn catalog(tag: &str, source: &str) -> Catalog {
    let Ok(id) = tag.parse::<LanguageIdentifier>() else {
        // The tag comes from a directory name; a malformed one cannot be
        // selected and only serves as a fallback bucket.
        return Catalog {
            id: BASE_LANGUAGE.parse().expect("base language tag is valid"),
            bundle: FluentBundle::new(vec![]),
        };
    };

    // A broken translation must not take the app down: keep whatever parsed and
    // fall back to the base locale for the missing identifiers.
    let resource = match FluentResource::try_new(source.to_owned()) {
        Ok(resource) => resource,
        Err((resource, _errors)) => resource,
    };

    let mut bundle = FluentBundle::new(vec![id.clone()]);
    let _ = bundle.add_resource(resource);

    Catalog { id, bundle }
}

/// Clamp a count into the number type Fluent understands.
fn to_number(value: u64) -> i64 {
    i64::try_from(value).unwrap_or(i64::MAX)
}

/// Remove the Unicode isolation marks Fluent wraps around placeables.
///
/// They are useful for bidirectional text but would show up as stray characters
/// in a plain monospace UI.
fn strip_isolation(text: String) -> String {
    if text.contains(['\u{2066}', '\u{2067}', '\u{2068}', '\u{2069}']) {
        return text
            .chars()
            .filter(|character| !matches!(character, '\u{2066}'..='\u{2069}'))
            .collect();
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_base_locale_is_shipped() {
        assert!(
            SHIPPED.iter().any(|(tag, _)| *tag == BASE_LANGUAGE),
            "the base locale must be embedded"
        );
        assert!(SHIPPED.len() >= 2, "expected more than one locale");
    }

    #[test]
    fn unknown_language_falls_back_to_the_base_locale() {
        let i18n = I18n::for_language("it");
        assert_eq!(i18n.text("status-ready"), "Ready");
    }

    #[test]
    fn a_regional_tag_selects_its_language() {
        let i18n = I18n::for_language("es-ES");
        assert_eq!(i18n.text("status-ready"), "Listo");
    }

    #[test]
    fn plural_forms_are_resolved() {
        let i18n = I18n::for_language("en");
        assert_eq!(i18n.count("detail-modules-found", 1), "1 module found");
        assert_eq!(i18n.count("detail-modules-found", 3), "3 modules found");
    }

    #[test]
    fn placeables_are_substituted_without_isolation_marks() {
        let i18n = I18n::for_language("en");
        assert_eq!(i18n.progress("label-find-counter", 2, 5), "2 / 5");
    }

    #[test]
    fn each_shipped_locale_translates_the_interface() {
        let expected = [
            ("en", "Modules"),
            ("de", "Module"),
            ("es", "Módulos"),
            ("fr", "Modules"),
            ("lv", "Moduļi"),
            ("ru", "Модули"),
            ("zh", "模块"),
        ];
        for (tag, modules) in expected {
            let i18n = I18n::for_language(tag);
            assert_eq!(i18n.text("label-modules"), modules, "locale {tag}");
            assert_eq!(i18n.text("app-title"), "MikroTik RIF Viewer");
        }
    }

    #[test]
    fn every_locale_defines_the_base_identifiers() {
        let base: Vec<&str> = source_of(BASE_LANGUAGE)
            .lines()
            .filter_map(identifier)
            .collect();
        assert!(base.len() > 30, "the base locale looks unexpectedly small");
        for (tag, source) in SHIPPED {
            let translated: Vec<&str> = source.lines().filter_map(identifier).collect();
            for id in &base {
                assert!(translated.contains(id), "{tag} is missing {id}");
            }
        }
    }

    #[test]
    fn slavic_and_baltic_plurals_resolve() {
        let ru = I18n::for_language("ru");
        assert_eq!(ru.count("detail-modules-found", 1), "найден 1 модуль");
        assert_eq!(ru.count("detail-modules-found", 3), "найдено 3 модуля");
        assert_eq!(ru.count("detail-modules-found", 5), "найдено 5 модулей");

        let lv = I18n::for_language("lv");
        assert_eq!(lv.count("detail-modules-found", 1), "atrasts 1 modulis");
        assert_eq!(lv.count("detail-modules-found", 2), "atrasti 2 moduļi");
        assert_eq!(lv.count("detail-modules-found", 10), "atrasti 10 moduļu");
    }

    #[test]
    fn footer_message_renders_version_and_platform() {
        let i18n = I18n::for_language("en");
        let mut args = FluentArgs::new();
        args.set("version", "0.1.0");
        args.set("os", "macOS");
        args.set("arch", "aarch64");
        assert_eq!(
            i18n.render("footer-build", &args),
            "v0.1.0 · macOS · aarch64"
        );
    }

    #[test]
    fn unknown_identifier_is_returned_unchanged() {
        let i18n = I18n::for_language("en");
        assert_eq!(i18n.text("missing-identifier"), "missing-identifier");
    }

    /// The embedded source of one shipped locale.
    fn source_of(tag: &str) -> &'static str {
        SHIPPED
            .iter()
            .find(|(candidate, _)| *candidate == tag)
            .map(|(_, source)| *source)
            .expect("shipped locale")
    }

    /// The identifier at the start of a Fluent message line, if there is one.
    fn identifier(line: &str) -> Option<&str> {
        let (head, _) = line.split_once('=')?;
        let head = head.trim();
        if head.is_empty()
            || !head.chars().all(|character| {
                character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
            })
        {
            return None;
        }
        Some(head)
    }
}
